name: release-to-maven-central
on:
  workflow_dispatch:

env:
   GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
   GPG_SIGNING_PASSPHRASE: ${{ secrets.GPG_SIGNING_PASSPHRASE }}
   OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
   OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
   SONATYPE_REPOSITORY_ID: ${{ secrets.SONATYPE_REPOSITORY_ID }}
   SONATYPE_PROFILE_ID: ${{ secrets.SONATYPE_PROFILE_ID }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Will start a Maven Central upload"

      - uses: actions/checkout@v2

      - name: Set up Maven Central Repository
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish package
        run: ./gradlew publishAllPublicationsToOssRepository Supacompose-Auth:publishAllPublicationsToOssRepository Supacompose-Postgrest:publishAllPublicationsToOssRepository Supacompose-Storage::ublishAllPublicationsToOssRepository

  #closeAndRelease:
  #  needs: [publishLinuxJVMJS, publishWindows, publishMacOS]
  #  runs-on: ubuntu-latest
  #  steps:
  #    - run: echo "Closing and releasing package"
#
  #    - uses: actions/checkout@v2
#
  #    - name: Set up Maven Central Repository
  #      uses: actions/setup-java@v1
  #      with:
  #        java-version: 8
  #    - name: Grant execute permission for gradlew
  #      run: chmod +x gradlew
  #    - name: Publish package
  #      run: ./gradlew closeAndRelease

