name: Release to Maven Central
on:
  workflow_dispatch:
    inputs:
      close_and_release:
        required: false
        default: true
        type: boolean

env:
  ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_SIGNING_KEY }}
  ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_SIGNING_PASSPHRASE }}
  #ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.OSSRH_USERNAME }}
  #ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.OSSRH_PASSWORD }}
  ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.TOKEN_NAME }}
  ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.TOKEN_KEY }}

jobs:
  publish:
    runs-on: macos-latest
    steps:
      - run: echo "Publishing to Maven Central..."
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.0.1
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
          cache-read-only: true
      - name: Publish and release
        if: inputs.close_and_release == true
        run: ./gradlew -DLibrariesOnly=true publishAndReleaseToMavenCentral --configuration-cache
      - name: Publish
        if: inputs.close_and_release == false
        run: ./gradlew -DLibrariesOnly=true publishAllPublicationsToMavenCentral --configuration-cache
